diploma_project/finproject/fin/urls.py
from django.conf.urls import url
from django.urls import path, include

import fin.views as fin
from . import views
app_name = 'fin'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_portfolio/', fin.PortfolioCreateView.as_view(), name='create_portfolio'),
    path('update_portfolio/<int:pk>/', fin.PortfolioUpdateView.as_view(), name='update_portfolio'),
    path('detail_portfolio/<int:pk>/', fin.PortfolioDetailView.as_view(), name='detail_portfolio'),
    path('delete_portfolio/<int:pk>/', views.delete_portfolio, name='delete_portfolio'),
    path('portfolio/add_stock/<int:portfolio_id>', views.add_stock, name='add_stock'),
    path('remove_stock/<int:portfolio_id>/<int:stock_id>/', views.remove_stock, name='remove_stock'),
    path('calc_portfolio/<int:portfolio_id>/', views.calc_portfolio, name='calc_portfolio'),
]

diploma_project/finproject/finauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
import finauth.views as finauth
from . import views
app_name = 'finauth'
urlpatterns = [
    path('register/', finauth.FinUserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

diploma_project/finproject/finproject/urls.py
from django.contrib import admin
from django.urls import path, include

import fin.views

urlpatterns = [
    path('', fin.views.index, name='main'),
    path('admin/', admin.site.urls),
    path('fin/', include('fin.urls', namespace='fin')),
    path('finauth/', include('finauth.urls', namespace='finauth')),
    path('select2/', include("django_select2.urls")),

]

diploma_project/finproject/fin/models.py
from django.db import models
from finauth.models import FinUser


class Portfolio(models.Model):
    name_portfolio = models.CharField(max_length=200)
    date_update = models.DateField(auto_now=True)
    data = models.TextField(blank=True)
    colors = models.TextField(blank=True)
    user = models.ForeignKey(FinUser, on_delete=models.CASCADE)
    volatility = models.FloatField(null=True)
    portfolio_return = models.FloatField(null=True)
    sharp = models.FloatField(null=True)

    def __str__(self):
        return f'portfolio_name: {self.name_portfolio}, data:{self.data} ', \
               f'portfolio return: {self.portfolio_return} ', \
               f'volatility: {self.volatility} ', \
               f'sharp: {self.sharp} ', \
               f'date of update: {self.date_update}' , \
               f'owner: {self.user}'


class Stock(models.Model):
    figi = models.CharField(max_length=50, blank=True)
    ticker = models.CharField(max_length=50, blank=True)
    currency = models.CharField(max_length=50, blank=True)
    lot = models.IntegerField(null=True)
    name = models.CharField(max_length=200)
    price = models.FloatField(null=True)
    date_update = models.DateField(auto_now=True)
    desc = models.TextField(blank=True)
    portfolio = models.ManyToManyField(Portfolio)
    user = models.ManyToManyField(FinUser)

    def __str__(self):
        return f'name: {self.name} ticker:{self.ticker}, ' \
               f'date {self.date_update}'

diploma_project/finproject/fin/forms.py
from django import forms


class CalcForm(forms.Form):
    token = forms.CharField(label='Your token', max_length=200)
    months = forms.IntegerField(label='Calc period - number of months')
    number_iter = forms.IntegerField(label='Enter number of iter')
    risk = forms.FloatField(label='Enter free risk rate, %')

diploma_project/finproject/fin/views.py
import json

from django.shortcuts import render, redirect
import requests
from datetime import timedelta, datetime

from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView
from numpy import unicode

from fin.forms import CalcForm
from fin.models import Portfolio, Stock
from finauth.models import FinUser
from fin.service.service import calc, colors

import pandas as pd

from django.http import Http404, HttpResponse
import json
import django.apps as apps

API = {'tinkoff': 'https://api-invest.tinkoff.ru/openapi/market/candles'}


def index(request):
    user = request.user
    if user.is_anonymous:
        return render(request, 'fin/index.html')
    else:
        model_user = FinUser.objects.get(id=user.pk)
        context = {'user': model_user}
        return render(request, 'fin/index.html', context=context)


class PageTitleMixin:
    page_title = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        return context


class PortfolioDetailView(PageTitleMixin, DetailView):
    model = Portfolio
    page_title = 'Portfolio detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = self.get_object()
        context['data'] = json.loads(instance.data)
        context['colors'] = json.loads(instance.colors)
        return context


class PortfolioCreateView(PageTitleMixin, CreateView):
    model = Portfolio
    page_title = 'Portfolio Create'
    success_url = reverse_lazy('fin:index')
    fields = ['name_portfolio']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PortfolioUpdateView(PageTitleMixin, UpdateView):
    model = Portfolio
    page_title = 'Portfolio update'
    success_url = reverse_lazy('fin:index')
    fields = ['name_portfolio']
    template_name = 'fin/portfolio_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = super().get_object()
        stocks = Stock.objects.exclude(portfolio__stock=obj.id)
        context['stocks'] = stocks
        return context


def delete_portfolio(request, pk):
    portfolio = Portfolio.objects.get(id=pk)
    portfolio.delete()
    return render(request, 'fin/index.html')


def add_stock(request, portfolio_id):
    portfolio = Portfolio.objects.get(id=portfolio_id)
    stock_name = request.POST['add_stock']
    stock = Stock.objects.filter(name__startswith=stock_name).first()
    portfolio.stock_set.add(stock)
    return redirect('fin:update_portfolio', portfolio_id)


def remove_stock(request, portfolio_id, stock_id):
    portfolio = Portfolio.objects.get(id=portfolio_id)
    stock = Stock.objects.get(id=stock_id)
    portfolio.stock_set.remove(stock)
    return redirect('fin:update_portfolio', portfolio_id)


def calc_portfolio(request, portfolio_id):
    if request.method == 'POST':
        form = CalcForm(request.POST)
        if form.is_valid():
            # preparing data
            # grab params from the form
            token = form.cleaned_data['token']
            # calculate period of time
            number_iter = form.cleaned_data['number_iter']
            risk = form.cleaned_data['risk'] / 100
            delta = timedelta(days=form.cleaned_data['months'] * 31)
            time_today = datetime.now()
            time_past = time_today - delta
            # formatting data for api request
            time_today = time_today.strftime("%Y-%m-%dT%H:%M:%S%z+03:00")
            time_past = time_past.strftime("%Y-%m-%dT%H:%M:%S%z+03:00")
            # get list of stock
            portfolio = Portfolio.objects.get(id=portfolio_id)
            stocks = portfolio.stock_set.all()
            # preparing headers
            headers = {'Authorization': 'Bearer ' + token, 'accept': 'application/json'}
            # process request data from api
            df = pd.DataFrame()
            for stock in stocks:
                payload = {'figi': stock.figi, 'from': time_past, 'to': time_today, 'interval': 'month'}
                response = requests.get(API['tinkoff'], headers=headers, params=payload)
                dump_data = response.json()
                dates = [date['time'].split('T')[0] for date in dump_data['payload']['candles']]
                tmp = pd.DataFrame({stock.name: [prices['c'] for prices in dump_data['payload']['candles']]},
                                   index=dates)
                df = pd.concat([df, tmp], axis=1)
            portfolio_data = calc(df, number_iter, risk)
            portfolio.date_update = datetime.now()
            portfolio.data = json.dumps(portfolio_data['data'])
            portfolio.volatility = portfolio_data['vol_ret']['Volatility']
            portfolio.portfolio_return = portfolio_data['vol_ret']['Returns']
            portfolio.sharp = portfolio_data['Sharp']
            colors_list = []
            for color in colors(len(stocks)):
                colors_list.append(color)
            portfolio.colors = json.dumps(colors_list)
            portfolio.save()
            return redirect('fin:detail_portfolio', portfolio_id)
        else:
            return render(request, 'fin/calc_portfolio.html', {'form': form})
    else:
        form = CalcForm()
        return render(request, 'fin/calc_portfolio.html', {'form': form})

diploma_project/finproject/fin/templates/fin/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900|PT+Sans&display=swap&subset=cyrillic" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'fin/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %} Optimal Portfolio {% endblock %}</title>
    {% block style %}{% endblock %}

</head>
<body>

    <!-- Header -->
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <a class="header__logo" href="#" data-scroll="#intro">
                    <img src="{% static 'fin/images/logo.svg' %}" alt="Portfolio">
                </a>
                <nav class="nav">
                    {% if user.is_anonymous %}
                        <a class="nav__link" href="{% url 'finauth:register' %}">Sign In</a>
                        <a class="nav__link" href="{% url 'finauth:login' %}">Log In</a>
                    {% else %}
                        <a class="nav__link" href="{% url 'finauth:logout' %}">Log Out</a>
                        <a class="nav__link" href="{% url 'fin:index' %}">Portfolios</a>
                    {% endif %}
                </nav>
            </div>
        </div>
    </header>


    <!-- Intro -->
    <div class="intro">
        <div class="container">
            <div class="intro__inner">
                <div class="intro__text">
                    <h1 class="intro__title">
                        <span class="intro__title-amp"></span>
                        Optimal<br>Portfolio
                    </h1>
                    {% block intro %}
                    <div class="intro__countries">This site helps you to create profitable portfolio </div>
{#                    <button class="btn  btn--block  btn--orange" type="submit">#}
{#                        <span>Create Portfolio</span>#}
{#                    </button>#}
                    {% endblock %}
                </div>

            </div><!-- /.intro__inner -->

        </div><!-- /.container -->
    </div><!-- /.intro -->

    <div class="main">

        <div class="container">
            {% block main %}{% endblock %}
        </div><!-- /.container -->
    </div>
    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <a class="header__logo  header__logo--black" href="#" data-scroll="#intro">
                <span class="header__logo-text">Optimal Portfolio</span>
            </a>

            <nav class="footer__nav">
                <a href="#">Terms &amp; Contidions</a>
                <a href="#">Privacy Policy</a>
            </nav>
        </div>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

diploma_project/finproject/fin/templates/fin/calc_portfolio.html
{% extends 'fin/base.html' %}
{% block main %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="send">
</form>
{% endblock %}

diploma_project/finproject/fin/templates/fin/index.html
{% extends 'fin/base.html' %}

{% block main %}
{% if not user.is_anonymous %}
    {% if user %}
    <ul>
    {% for portfolio in user.portfolio_set.all %}
        <li><a href="{% url 'fin:detail_portfolio' portfolio.id %}">{{ portfolio.name_portfolio }}</a></li>
        <a href="{% url 'fin:delete_portfolio' portfolio.id %}">Delete portfolio</a>
    {% endfor %}
    </ul>
{% else %}
    <p>No portfolios are available.</p>
    {% endif %}
    <p><a href="{% url 'fin:create_portfolio' %}">Add portfolio</a> </p>
{% endif %}
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <div>
        <canvas id="myChart"></canvas>
    </div>
    <script src="{% static 'fin/js/chart.js' %}"></script>
{% endblock %}

diploma_project/finproject/fin/templates/fin/portfolio_detail.html
{% extends 'fin/base.html' %}
{% block main %}
 <h2>Portfolio</h2>
    {{ object.name_portfolio }}
    <a href="{% url 'fin:calc_portfolio' portfolio.id %}">Calc portfolio</a>
    {% if object.stock_set.count > 0  %}
        <ul>
        {% for stock in object.stock_set.all %}
            <li> Name: {{ stock.name }} </li>
            <li> Ticker: {{ stock.ticker }}</li>
            <li> Currency: {{ stock.currency }}</li>
            <p> </p>
        {% endfor %}
        </ul>
    {% else %}
        <p>No stocks are available.</p>
    {% endif %}
    <a href="{% url 'fin:update_portfolio' portfolio.id %}">Update portfolio</a>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <div style="width:600px" >
        <canvas id="myChart"></canvas>
    </div>
    <script>
        const val = [
            {% for value in data.values %}
                {{ value }},
            {% endfor %}
        ];
        const labels = [
            {% for key in data.keys %}
                "{{ key }}",
            {% endfor %}
        ];
        const colors = [
            {% for color in colors %}
                "{{ color }}",
            {% endfor %}
        ];
        const data = { labels: labels,
            datasets: [{
                data: val,
                backgroundColor: colors
    }]
        };
        const config = {
            type: 'pie',
            data: data,
            options: {}
        };
         const myChart = new Chart(
            document.getElementById('myChart'),
            config
        );
    </script>
{% endblock %}

diploma_project/finproject/fin/templates/fin/portfolio_form.html
{% extends 'fin/base.html' %}
{% block main %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save">
</form>
{% endblock %}

diploma_project/finproject/fin/templates/fin/portfolio_update.html
{% extends 'fin/base.html' %}
{% block main %}
 <h2>Portfolio</h2>
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <input type="submit" value="update">#}
{#    </form>#}
    {% if object.stock_set.count > 0  %}
        <ul>
        {% for stock in object.stock_set.all %}
            <li> Name: {{ stock.name }} </li>
            <li> Ticker: {{ stock.ticker }}</li>
            <li> Currency: {{ stock.currency }}</li>
            <a href="{% url 'fin:remove_stock' object.id stock.id %}">Remove stock</a>
        {% endfor %}
        </ul>
    {% else %}
        <p>No stocks are available.</p>
    {% endif %}
    <p>Edit portfolio</p>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>

    <form action="{% url 'fin:add_stock' object.id %}" method="post">
        {% csrf_token %}
        <label for="add_stock">Your name: </label>
        <input id="add_stock" type="text" name="add_stock" class="form-control" placeholder="Stock" list="stocks">
        <datalist id="stocks">
            {% for stock in stocks %}
                <option value={{ stock.name }}></option>
            {% endfor %}
        </datalist>
        <input type="submit" value="Добавить">
    </form>
{% endblock %}